# yaml-language-server: $schema=https://harryvince.github.io/danger-go/schema/danger-go.schema.json
rules:
  max_changed_files: 50
  require_pr_title_pattern: ".+"
  require_conventional_commits: true
  require_squashed_commits: warn
  required_files:
    - go.mod
  forbidden_files:
    - "*.tmp"
